---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-assistant-music
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 172.16.20.5
    path: /danscrib/musik/FLAC
    readOnly: true
