---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-assistant-data
  namespace: music-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-assistant-music
  namespace: music-assistant
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: music-assistant-music
  resources:
    requests:
      storage: 1Ti
