---
apiVersion: v1
kind: Namespace
metadata:
  name: velero-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: velero-test-data
  namespace: velero-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-test
  namespace: velero-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero-test
  template:
    metadata:
      labels:
        app: velero-test
    spec:
      nodeSelector:
        m8t.io/storage: sd
      containers:
        - name: velero-test
          image: busybox:latest
          command: ["sh", "-c", "while true; do sleep 3600; done"]
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: velero-test-data
