---
apiVersion: v1
kind: Node
metadata:
  name: node1
  labels:
    node-role.kubernetes.io/worker: ""
    m8t.io/storage: sd
    m8t.io/image-cache: "true"
---
apiVersion: v1
kind: Node
metadata:
  name: node3
  labels:
    node-role.kubernetes.io/worker: ""
    m8t.io/image-cache: "true"
---
apiVersion: v1
kind: Node
metadata:
  name: node4
  labels:
    node-role.kubernetes.io/worker: ""
    m8t.io/storage: sd
    m8t.io/image-cache: "true"
