---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: heartbeat-url
  namespace: monitoring
spec:
  encryptedData:
    url: AgAfX0QEUIEuOouRlh8Z8vM0IM2jc4Dd0TbZ2GKVAQkNf6mePd5dSeq2054oYL0GKsJaK4vpJWwvo0fsnv8ftL/P98cX329zp5QbgvHVzzAKIaGyJ9k7jyCNFZQH5Fx9kLg8oWwVZ9/9kBY3Zz4RUJNV4Z+GB5Jr76+1pjKc1GdQhcAZwoaC5pYO8a0x3f5YPzbJKOtwiY1U8IW6mRqZVd9Wv1lkCWiH/WgUKNL69ifh3S59ELEHq1w277pHjci8HL8hKN800nDHKjOI3gy0KSxrB/Bw2DRi5LL4rZTt2NtcV0nuEttAwDtdCTDYr+LpmMyZ1zM/7hSPjOX+5E3r3wtla7tSAFuCw+ATQgv299tTRYu4tGa3Lr/XqA/DS3l69TvOszDNYxlaL0Y/D0H99i1eYbUAX9zMQz35yryycuRl75UHW6a9u9Jy1VITswQqJoWc4teCFccE8fpgYbqH35yjVIFFpyl1PJ7eL2surRsZdOTrEKLTQrMlT34svRnpnVOR66uEnpqx2Q5Yu4TJXEtbesQ8rsJVIyhFvUtTVPpp2e/VWUb2HZkp1RieqKO/SUlgefHYHTpupLZIiE9/soCIf8sv6x0hQwIaZCBza4HptHQNjP7Lymkq1COogHBCdTokOTh9hoP4ib8alCBIeCvhy4FxxMcBAyMpVpvEbULvCwxfY2dKQXEAZI8mtYuk0p7vUVWx0K/RrNcGX+74ojbcubbvJyRe/piE4wLcsk2aDN+ySXBMly9kAzxviQm0MCUN9M8OSlVIlQ==
  template:
    metadata:
      name: heartbeat-url
      namespace: monitoring
