---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vps-sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: vps
  source:
    repoURL: https://bitnami.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: "2.19.1"
    helm:
      releaseName: sealed-secrets
      values: |-
        secretName: "sealed-secrets-key"
        keyrenewperiod: "0"
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            memory: 128Mi
  destination:
    server: https://10.99.0.1:6443
    namespace: kube-system
  syncPolicy:
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
    automated:
      prune: true
      selfHeal: true
