---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-credentials
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgBUM1lM/OkPO40ctFWEX3kmrt29n7uEACE+ES2A3H6/HITdUPPnWwQoT8QYef62emZJ4EdVWx5KWQAGdBokA39cPBC9fc1WM4juPQeTrPKwDH8i2SV4CfBfLDtCRCAG83H/MhDUvzr0WkQdtLAtxrQALzwNJLxu6Pqw2f8lr2VTrT7lXSZQo2WdaZ6XgYNEBF3UyfWXOhEdJaVh4YNVJpdqn3Yc3P6M8Kijbj4tX+WIxYPpkk46/jB/IpT+hvHH+svaRhUMBQb3n3i/ICKOfxNNohgDhF6cTq3iwyYhTY2DkUARPNHUPKqQxfRVf/EA1t/TGwUh6vY3i4lX+mgvDFr5od76l4e0YDzHQPjQ9Nd6/TFCB9LoglSm0f3jNSJxJ0CAADHVrS/t0KXU4v8xX6cZDP4FZbZb83SimSilzL6cwSUlsMbw8hmRorpk3l8Ug1QJFRcXDXAEyfUXXrUe1Ti6kLs88xLxqhyhLPKBAMP1tF/H//0MyTkLUV/YWFr2o0iUbhdnR30IIr1QKIdBnJ3p/cnoeHbOPudRbZNb01L5QDXZ/GTTBPT/mo81qJ0TALafKRXnTXWYKikdoaJA92XOsWHBt5oOtgJIvijHEp8KE/O4kygM7byCidgMHvNbpbhhv42YUJRdDC3RGPnxKVxafKKlqsHjkQTjF3Uc1AIvC0v+Mqukk9LVmirZ9+ep9Nz3kzg8bjw=
    RUSTFS_SECRET_KEY: AgA2R8LR7VaCxLeIE/UNKO9ie4xRuQxO12IeH/ALHaMkPAIBWpw94VIdqeR418/jMnIeDU8bQSVvHdfBI4vKFUUyc7DjK18lpuxS39eRI2PtnqBJFV/jCJ4dSMEvJHlZTLcNOJbU58B3SMR6NQ1W69ScZLfVs3vdDS7rqqTTTP6wfUuAO8eCS94YdtoqgJVOLijxcrmV8JLFvOQgiH1cJ6QJw1OiRFW/2UYdNF7Xm/MW7z9bvtZLsFW2orh8qyTr46LyV6ogo2HJf9uNA5jKJwksydbYezaXiqG1n4uDo6aCXAM4T/CeLBUDbT8H4mv/HNNdNjRoiLJk/Da4awf/CUPz6KQ0OTAo8Sv9eZ4BEIywkPygi2fplvjHMw6nnKXrGqspIWFkZ1niiJJa5kmwaDosu7N9zmnVOsk7TseWjmGNYfln8VGm2ayTlZDQKimJZDW2OLnwucaxp+BXDCDUDp9sxzXfkASqcKZDYah8iv1BZ/NwjZjfTXxqcOKn+yqMfMgqaCa2aqIEs5mT4cWBP5rwaLxBO9Zj/95csLgvqYl03A+jXkA8Q0NohZfW3QqmlPkGvxzfoeVhyR5RA+9XvfDl2cCzdcNUup4luomjVmKHw6MrAQ6wwrQAa9C2o2BPeLFDl+bUZ+vugq8KppBr3hUCyTJ/xBd9wzXtYi8C0cEdBkF7ZS9hf8Jb3iyKaUa50Z26LRHv/MEz9EshsAY=
  template:
    metadata:
      name: rustfs-credentials
      namespace: rustfs
