---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-postgresql
  namespace: vaultwarden
spec:
  encryptedData:
    postgres-password: AgA9sQzHv9hG+LsnHb8S8MQRlFQunEDCBncwqc9KxxsTsJ05ngxqZ4mafq49iDlbCVCy/Fk5HVjOI46cOINnKopIWKk6UNXVaV/RoKCABoIpv/DoRKb83lYkZjFY4ull4UEt4w3gpMMNvJaTqd4Xu0mOQKuVMiF3eFp1pfZHV5FMUUFeWi4X557+mo/VORtAYxbutgY/DQjoOFOUnPgXZh65mrg29vKo3zubHEG6iN3i6XYG9PNXzPj012I8PIMb4d59wWFr/w3uH3+5o92gqQf/V3WGwSYKhYP7prNtGqQCgRamITe6clBjJynyA1aU96LQcU6oTS1ddk5H8pdncyWNR3X4YkUZCHCLXwLdpaj495jIpQT8oKBr8RzaNmvI5CX2QsiKovPnesEWHMhqZXMk+DpXCQFaxHUD2Mm3XSm9+TQ7G3l0ajg4ptJod/hgy/Oy61dPvO/uJSy0w5f3gfl11tj4sME64mwMUm9DIwn79Osp5kZIUMwV1pXzquyvldwP2k72CqsbldY3j3XCQrMeLouuzRmIJlRLnKm4ttjQBCVia6XWr0FltPBf4OIMtqP5ULlXfJIG7QZfkPHy7UGHMlg+naaT3AMpz59DhLhNuOn0Qu/cpDoXBptpoPG45t3p5eRAk1xjcOEsoe6k7If84yojK+N3QI7+xk8Z0eLItB2tLWH9FzpmcwRbhHmaw+4N3ceEFpfcUNxfX5qEMd92y3AJt4G1V6TA4UmYd85OYbGyj+rdwRz16UHW
  template:
    metadata:
      name: vaultwarden-postgresql
      namespace: vaultwarden
