---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-deploy-token
  namespace: docs
spec:
  encryptedData:
    token: AgA61UCRONbsH+8Pb0I266a1EPHxJ7waqdQf8pwRRak+S67JMi5NOuNCXnn9IrgOUptjbn79aJ8KPBHaN2V2dAU+FnyNLbD8qH/KfAvO4dP+sUkQRePeUBQ/A701l3P0WHSG70rclce/6Qz/1j/bVqw7WvXsC1wjO0/rJ2CnpXl7xVZRiOUJpHaHmgart+EDSYDqQTSog9dPfirtOzR9GZ7hJPhYM27yUcn/V8amgM+cezDUyraMtpBlSsKy08D2minid4E+0j2RQ6+89TMbUg59jd9BLgGeBIgKMNAY7CDHiaRqQCLqTq0BYpPKJtNNM2M/4q7dsolLd0TrwT9g8vzXan6tSqISpleNWFkdr+V7l/+R1bHI+5ccW2fiupbJAPIQDwci2SZPhd0TRvuK5xdXmR+e7rqBBbUHSiNsp+Ve9tFzkkv8foATWURb7FS3Ek8u3CorPOch4r/vguQaub87CaJauj99sKI7+OpNpSaTWVZfVlz583wLtWnowoz8oamiMDUC5QfssYjKth+0zrnUCTn7Lbah5nI/Zc9KV8EMbGVora+OfssixJcoGC0IM/bNuAmu+3iqI33741m5n6pfBorns7X5y6C9+hx+3hgeDKLCnegbEqp8v//VvDuY3yoYyMh8huTp613XUJr+60xwQ/5fy3Tj++jIaI3+/qDf4wsJk4YgMbsOzUSeU70QC9nkmpMLtD+k0mnWKpO4hf2dJ6dpMmKKC07P
    username: AgB4S9oWF7q1UkF5Y6dufwmw8YWBbCHlt7TTvZ/JxcYPFCOoxUVLFZSvPn0ptJzMjn39peA2sDjZWI87bQ/UO/9dYdYuERcAYWOPVg5jOsLmDP9QXVc6LCU/Obj+9Zns8/+l5Kzw0kdO/vuz6Y1hgaytIX+xajtyld1Wwuvev+B5urWS++MVahegCuQlfXrCNaZ230gpAFuLEabsHUkeoB2rP5VoUo52Ejq3qoRsfoP3rzXK3qJMefT+7PYYOGRUhsc4Q5878YgLwfUAuq8NOwnMYHndiB1jHLF141FHI3CK7zO4CW9ZzgmZ82iCcHi0269++HANcprl7mpUxy5dostrv+GE/hr8+i0Kvj/Upp+8i5C36AlbgB0YGFkOa2KzoUeVlwPUjNyk43q7hnkORUKVRYa/xhRHYuxiVWix71IBlnSNiyfyiKY7VS04YPp+jrRhjUQQ3BZAuRBrms9PnqQ/itMI3QmACHl0UHnSBO8T15sMe5wVejBqP6xohpHLbO1C98Nsbumfq16T4vakqwb6gHgM/6NcrsFysM979yO2IFFlER8L+OwkW9ZY5LnNrCV8/5Ouu+JAGKQta8eqMN+J9X0eMMKx9fi+CSG6pu5J2iZgqHA4vAFqhCFtue/XGVjKOtUxjiEPK1fNcmdVvvqzRUV1BOgTVkplDQ3kL77PaSRQ0yHe3H3FY8bUWAnSQScxNEtHiqs=
  template:
    metadata:
      name: gitlab-deploy-token
      namespace: docs
