---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkwarden-meilisearch
  namespace: linkwarden
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgA9UCecUAPdysS7JqENkjur3Oy/iF90gBhlPKLWJa5KRf2F1B4hGHMqQOdLKH3Lffbw6Lkil6Hp2Hp6JZaW8QtaHuYVjUnAhzCeokys6TWIPKnimXyFE5HlQ9jdfejPpUw4oftPvFT1RdTjEaluBlnsHV4cLc2x1lSBGUixMjeSeePgBICK9Fo06aRcfcIM1+R03/w+64xjkcxYNdC8enl1WzvC0OhHGKS7bfrtzf49tZNTBDfMotF4oekxATGjeLCie7fIgCu5uKjKD86q8Kc8y00SgT5XmWv823rj0pp0+xierTiWLPLMWKiRiXowiD4zjBEXCztYILr1e/GL4vfuyRj+bK+VpVjRwZoWqDjHtfED2YErlQL8AULD4SmqR1UMUyftMgN3FFaIOrnm7egq9twnUvM1JEfYaX8yZPqucJZHdWjCfb0LyI/eDdju/w/NDwNTdI+1uDZEsRcAA2ESxpdXAP7yBeYe62xjIWOa8juCDtEKwU/4ft+xkKgk6+8ISAplC9rP9gFiSuYA9lJ74xane+QtMZAQBfPFM4JONpBWypNB1oMuRCzm8956Jt7hQ4SxDlYk+4OnUL4MRpV5Za9RvWO0J6t/wV/J7Nf0zc9INTM2sUNUFWfq0hXNtOTonWGUNERuA3z5zWm4+1JzmjUNc9e52tMjL4zZ2oCOXDVb/8tO2jilyGrLKkGj0JgyDeugctTvK/IZd8YPQ8X202xBzUCtpmtO3Ltnwrob9+6pUax7ahvphyHDnTjNlvA=
  template:
    metadata:
      name: linkwarden-meilisearch
      namespace: linkwarden
