---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkwarden-nextauth
  namespace: linkwarden
spec:
  encryptedData:
    NEXTAUTH_SECRET: AgBuZNzGEObtV+uj+lNgpXu6/pD6KL8tuAWfmxV4gwd4RDInTKxHyJgjnOQCryCcODScBkYPxsuBnCkHH/FsqWCaavY9pOYJYgEeOr2KOpnbONOGdZaQltPfdR1duvX0rYiKxRP/3/VVvegbh2Qh8pgwuWs3+d3fGXYTFw6wB9t+Q7dnG6HxlzIrw1EKmtAGndr3r/zIK/7VnLxODBbp3AbihX0f2SafBguriQTQlZL6ZMUj7OPWg/++qS8aYy38U8bBAhwVtdkg5uG69jkXGwEjUxXrMy+cnhrbhXoYDUog5R4WBl+iEY8oL57dOjfgs0uaLMOQl5p6b+CKbcdJwVOOCIDH33CCR5sfUYC8+y71yAncxpmJU7AbxIKtflIr3diuktg+NBG20WEnKM84ot7oQ+Ei/FV/NPPzdvX+juVk4nTrK5ty1x965eVUav5gADGk+elqp6i/9r2uAiZpnStuA5C1xPq7vwe8PAKBHjG7tRQBYGhmuKHnuuqmE4gNCpFRkkickK2zBt2AnOhIV+Mpf5tmGLDBTOVo5jG+0oqXHhx3S+mhUSGDNEuInfKZrjSp/3aP1VWUuauMjDQvGtgZs3xQM9nhLtAOguAaeNV3vYOvfmSMz7jNQ3lQQt7NP/IZWPP1nMr4Sg1LA/PajkzF8YXvSvC/8v8wf48Pq9k/ArYmhlm0vGBj/Fi0L4z6fzO0h320liQdRVrr+sOpmajZgpc2riOtVWCVYAOnexQeQqrhoyAUiKh4SbrOJA==
  template:
    metadata:
      name: linkwarden-nextauth
      namespace: linkwarden
