---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-staging
  namespace: linkwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
