---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials-hetzner
  namespace: velero
spec:
  encryptedData:
    cloud: AgBaY7McQq+5ApsO/2S7joa8vaoSwTFCpCu3yGD16dQMrrSAbmpm9fiBleBoSDFsgwG7qpIBLX/CC7wqOTaw4Tf/xAvGZW134BfS8x/ZMEC93/PMggO7/vr6NX1dxpbqv/JQRJ+f8gWhntIAh8B21BOKiH9FrY71kP4TtSV+IGB0e1WCSPjBCOzGWu6p/2U9PuPm7h1BpRKbBRSskgvM2z2rRwCslUei264OAT0ZBK+vAHRbiiXHLHhpSFINhzD1OZQ2eG8okaBtMFuLueBssoE7JEzS46x6AmLYvWYvlv45oYpXDM+KJO6YsQmtFJkY8pAff1gGKkaernhmck4/nOjWgYUkyLJ4JJC2H2ME1Jbv+cLXQReto2yRp/gBiN4rkOZM5By+oEBfH9xxiEHmXAP5P6Me/lktvI5qDc0ST791+R57SsSDR2+DRp7ccwe3XEopP35o2REiL7/TBXoce1ar2uOsoOWczyOgqwoMp/aLAc4CfYhzLW3FRgVLMO7shSig1ZiYxhWJZcfIeu1pVkPgBViT/O6WWorTYY/ASCpscZlnqMDyW+L39/hX/6aEFbL3C+8hG4a/93xSF1cP9r8K40qSPtUJNoGGNoS0iCY9nuIM46lGVhflCamP+Y7EvnKpIbOndxCY5TpBsLxMtJdq7D/zfgsvsnYKUErTtphpacnWIIZFPfLP7XUta8/5qHHgquebqJRkXbvREYZ/2Tbt8dCTYTJ7GMwPO3D4w0YniVsIkwrCSskHppQOjTgclAFZWBrcKFWBuq2Z2ZyIQlic0ve8zBR1lAI0HYTQezG75NXJ1sBvPzbJAJAMGvS3nbTxXSsW9e7efu4J4YikbrxgP/OpPQ==
  template:
    metadata:
      name: velero-credentials-hetzner
      namespace: velero
