---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-sse-c-key
  namespace: velero
spec:
  encryptedData:
    key: AgAo9WriFf0vTCdQIPiEKMFbdHyZLyRPutTJavCBR6YyCy/QQZlEhUNoPACOvfPeSTB2XriU8S9JqrdRT4kk2x/l/eaxhdyUvU3DHc7OmHQlfG52HQHY7bF8bBEhMOy1eDlABuwXW5XJa++61CsUr7XCWGSLayRpv593Hx1d9SWAMWuYDmhGKsW3z8MoCBNQB38PwC8hLtoLFOP2Yw95Z3jzCeMUvIU2V2q/Rm3SgSindAZ4y2SH66WX5MZOoJztBiMakcR/50uwXURWXyRIX8vF0zGN3RaeQ7qd44uvi9vlifTKC+esjd+HyJDDDbGADhFdxL7l1Li6FzCmVtrGtkyZmOKwVZ5zi+3EtENgUbYJds/782Et2sA1JPekLRzTpJzCodL+3lpz8mGkHUVLrGN7L91HwYm0l+4WXgH0fmdHgyKnTNTnHQ2qLd48rOxBzcnwJSOSghwpZ0Vgb5G2p7deuBM86Tvj1au0lEdYEEwRWq/PTZ8+e8JpTYmb7uxW+fgyE+MWqk14bVxEi/VeKZRwXMy4+vmiscX8MJz/B26TdBOIfWFrEDjorkfFPnvPAfnrOU743KADxJ8B9WaYUqD+bd/R0IYBLztOoIBCIt66NZJaUz7YzQqpnQ45nzcymlMrgXiKFw0m0FA8TF+7dw8zhvEPyTeL1EZwOWlh8KB5wq9JkSc5ATaZ5H2uTWMyn8suH8XkGu7zRriPipma/UFzTE5o8kzAosx00c5RGwvPKQ==
  template:
    metadata:
      name: velero-sse-c-key
      namespace: velero
