---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-admin
  namespace: forgejo
spec:
  encryptedData:
    password: AgAclboi4Q8dRreOwhUcNpGmjgSiRF2GbVn/QDvjGLM1QPE+d1+/OJFmDclhf1KfmBchtsbFHV3L3sr6YFXTx5Y4z/U47ySbuNlJlHj14E3QJE6VxIQ7KoxYG2ex6UzRS0pmTj+HGTSms+BPI77omtef3feUk9sOyTO/3ZDJVRDgXSriX5mrMIJpUMbsIQtuAr2geZipJjXSgrgjnJM5ND2Y7ibEqfuh+5cD+CwrYU1uCDhQ0ivyL3FbmCIJl781ZuwcdfcgJJXVOMEYarr85LBJjkwkBUt3U3x1Elv2xDIRtKWyqtlwaV3O6F0cv6iZxwLZye4D43gB36N6qXiowQfhvs3cn7EjsVCc2Wx/Elj6mqaIF7vQHPRZ+urah9JVKFGm3R8BGiyYI1sAFuWb0js2k02wZTi33l9ZMFaJkai8vcshr7o5kUkaBMRKp0+IgRr3EIJBMZXSwvRl+uqZQ9oXeB6VIoOOW1bkalaMdCNv85cRHzufa/84/Jl1N7HV3uwsqR/8Qsrj7Ep6Mhnj/C8Yvd2mUWsvcCY5f9Rk5KEQ4m7KdRBHF5EJE85elqL8Bm+yO+CMr4fXGvd4Xa0OulNjCkWnfddSkroDKjC0Y9BV927jfbAI7Ux10fYXYiMDP8WaHnDQq17qIdztg654h9O2jBUZ7SC+XPdvAVSD6rT17KiBWpuQsMABD6vFlQK/TcP/jJx1O+JijMIg5sEgKctHQlhK/YssZPA=
    username: AgACTj7EgWqNc4qUaRj8gfUxWM1Y+e0EJ6eYZL+d49xW19oiEptL11DJsxlTHb9pA1kSl8aVYXfjY6PNumYO5kPqjEl2gsGVWspZCEe0oYMiH7B/xwz/vccMyd4XFkjTwPmXXFN8zldCigXBizClqhg6b0qrpFvpX9EpGUsGevNc5sTybqSn5zVc0zmkh9MUQqSTAFj3YtxBFYqrhhQlwcVesbDgCVl9Ur2E9tiZhu06oNtmSPfMaeX0uTh8XBC8hDz/L1rAGb6p2hnlaJPaRj0oSRq7nPTFHkHoDwx0xq8loYEBrmhDOn8jqs914vy9eK9E3riaH0CIwFXsEgQmitQyL0ZqPzb2CD2dGJg/xfAwBcgieSeSmBk92l9/UnL4qtXSJMUnlbmttzsPg1pjfmeApZuuQ8gLeqIlynMGUEKwRcPXgT6rUyFTLbEHMEWN7H3MZkphUEMhGflGumh4bD2sFy0/vdFdzaBGDh9T1D4NdoreQmEGWPjMHC/2Iuy4W1NJb8oe7+VDSancng8CjgILCCObExaFo8+mJiR6h9ITMEWSmcM/T1r1x1XI2WS0Tz3mY/8ivnvOsxfyOVP2ty0LfhGbigHbAgrxjAEontIV3MLV6z8sBIPi2ANMUG3GLqbx7kuTFZF86E7HdqzdSeQrBBWKoHwzOVPtjl0W64eGHlNU+TlIe5kvUjvzHlF8bXsHinoSkCyYklY=
  template:
    metadata:
      name: forgejo-admin
      namespace: forgejo
