---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-metrics
  namespace: forgejo
spec:
  encryptedData:
    token: AgBsgKnmv/23EoGxNDFZSc7EIcYlkhHNK34R+T6W5w6QlB5qKhvHFHWlABCPEeSBU4kuoOw6xm+9dkOoLlPrwP2Im04fSbf1Pftk5nVgOxT9nWgUvg3uJolv7vWze4dJsUGcadzmGLsBX4nNgA9ycQ7R1JZwBmOqD/lUeucfROSlsxsB6n5Ynd4ZphvXh8SAJsAkyRRWA9ZAPD28LhJlse1ERv4g0GkponQI1X8hoY0y3M+2U1h4XzR+GI17L3fEqUYqr/yIxc1aANgbOqXOSK7+Mr7j+HjFQ6+1ylJuyRPJBnvpQXNk/wf6J0inb5W2YH+nNIDQUmsmIcNgwxQLT2h90+UsgsZXJZFgFIwe7LLxi9VN7fmVlrWt4Dk8oI4piFo/Mow0t51M/y357YGWnetLCQVKi1IfsglI/nbg/IR1hTQZuEqwscv5Nh2FVP/57CkJZZfs9rqLuvjn+RvfmD5NYRgw2XdFHWZ+wFZsji9trt58IkIDOalLKyCPMG+wfQBHMJQrcFUa5LwxrVc4E40foxKAow81bCHKD4rQLUz1fQZomZZHo1FS+FrZGCYdqJNdT8SHH2ZTIMa4ulExZOVX+0bVAzkTvtLUfYQ1nmQ0C/86azJcnuhioKsKJiSpxkAMwr1SHZN6FuyIgxd4c2iFu+UCMofm3OYKUPJfTQys7YlDAwFK9FhHcVWofd0OUOekRdZGsz9NTL8Ci5VBFuoBawO06i9hdikk4c2xW79lhJ9PAjVdiWed9Xa3E3GbQ81slIqPcnxkk0OupI1bHnl/
  template:
    metadata:
      name: forgejo-metrics
      namespace: forgejo
