---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-config
  namespace: forgejo
spec:
  encryptedData:
    config.yml: AgChcTumdVWHOlXD8fCJnaqYTF6pXqa7XOX5nup2OzBW15Up1zwm9Z937FiWHs6X7xR5lz1hurvhUtLB0FzCGk/5guis6OZwtB6NhWbRtiDU/8ylTyAkmuMD+qVfZGVxRcSS0tfPXJDkA9Lp//vY0XKFOPFpIyoxXNWx9gHjk68evuYtGsGOk/niV9cV7YJ6tktVzYNpQwU7iiSuSBq1FhgSfos1KxCdSr6ezbg6tPSXFn4zTzNfRUy3x4IbgvbY0fQMu792iM44WpPQ5qLNSQ69d/ce+rOvqh0+2fPRuOOdDGRlmC8+2sLrB8nXibxbOrGccX7zb/DktKBdiLXpHwZQtdAKKITI1r3r3Hj/+V4CG3EEq+Re7b/RO8wdWpspoZhrVUS9qIFxCIfgoXzz4pVyxniR0Sd/CCZb2f12+NknM6SP2BgAto87oXSOmXQTPKSyB7Rst0DbQ/hldGxVcNYGg4FH5jkPdqR5DsEd1T74+mBXutoI1Ha0b7vm8KUBEIIaqMOoTDkw9uii3yjVe5IHaXsykD9mzua9jMh+jBAQR1/GHdc+1cczUH0usxEJlqp0W16H9zXyE94lqVTf7BTwMBxBe3xfoJuvfBiahx9jeN3mw5tDbcvP78y+h+/BkPjMSP8Y/UpibmsVOAWQg6YtxI3WH6zyea3yO4xqrw+AUjpxG3L8fsFtVXfRUZXZE8Kwf2gVzNNdfr4u9ytDU/yxQ2fYFOEks4Djznb1LccNZkYkc2nzWDZQB97hVKsZXslz2PlhFR3E1UDdKpmJov2EwZbvR4Koe2fRSETxR0k0kJ120BHDSkukKX7knZY18NQpY5tUbgawIzj5ACdXTzrOftlyWAGhIY5JH9fARXkYiSKeJzsetZDDR74+af8pIctsHPWGiihiyoqN8O22cfX+kJ9bkLBZrPKi/8haohXLSkpW1ZrdRq9boW4dVkpVB6GWC5bwXo+ncqASKKqMxbHvXjNcYv5Y8hTzgI0vNPHjMbuug5QC73oOV0jF12cerlIMobYPFRjaZ/8pBcIL9f1BDo1pNIHtcP6OYRFjIZE+ZK1m+aW3n9EYZfMNSWh55fonR2dwH7no3UwK7vWK2uRP014VWyqdr0HBBQBKU9fttK4776XCCzL0eyozLVWuhtzTHCe1JQi2s/K8QI/gyzdSJMPTtekDB8RtMDBxkbUo/D73bXK2iaMwnhRU93K4oP3MbpWzZ7//ZC211UNcEcMK10Cv/J3KAstFgJr6DIUompq1L81gEbQahPSIdW/6zXgOPsD/QxQ4Ey8CBGEvBnHlGxDCWII851+55dyl+YSPLw4Tj8Fp6Ng=
  template:
    metadata:
      name: forgejo-runner-config
      namespace: forgejo
