---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: yamtrack-postgres
  namespace: yamtrack
spec:
  encryptedData:
    password: AgCQfSVI2CBet4Xx5QSCz5ZKPhz6ncfmCKyU/xFlDUqqXG8NCQp3OukOln6ANdYtesS5btfvwgkZSWphaG96L0QM03XdZBby3TY7B1kWIeZkZ2rxiMOpijZu23nsWzaotewNBY/XVs+LT7dvbJP4kD1q1CJqSwciWO+KlViLApJk4jgq7wKrkNJfakr72/4PDCW6pVcFxNwDc3OcsW6HfRpPTn4VrfQqlt7BlIbilgW9LQSNZY27lWCSXycQnghp9RSb0bLY2jVyuHug6SqqvJe0VAV5pngEVAenr/fQXNST6RT+SPI+21PtUCk11lnLzIDtaldkW7fRKY/sRqjRsPbEnY4W7qoh9wli5cr06U1V+zpXL/roTm9+QwWC8/PZl5BAIVK2+15G9dQ0d0nUx1HRP831QCZxrVPAfLXZYXvVxl9y4dRwDmJwGMd+WbeOzL1qMCzKhyURaFxT3P+Z9+eL+z9gapOde/UnQIQaGyrJp5CJdhCiVSbF3UABxdnp/6TH2J0r+uaxYATXx2+oU9UgLN+HIZMEG2kD86t6rpGbXWou2f0Mv8XYeQeClX1kLMhrg/CEBo1hIB7KKRtx+tCaOtz7JYIBAHrAS1js5tAwoRS/au/auXQ4vVbDg4OSLH9xZfEEe0fF4YXfdRK/ri30MgYI7p9kaznZN0OCaUMRf9FTPJyoMU2XJ8diHwPyRifvNHyMud1WjnKBpSzBh95hun6pAmZJeIFrfGVpdD4qgWU7L5J/ffbvpVYtNg==
  template:
    metadata:
      name: yamtrack-postgres
      namespace: yamtrack
