---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yamtrack-redis
  namespace: yamtrack
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: yamtrack-redis
  template:
    metadata:
      labels:
        app: yamtrack-redis
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: redis
          image: redis:8.10.0-alpine
          args: ["--save", "", "--appendonly", "no"]
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 256Mi
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: yamtrack-redis
  namespace: yamtrack
spec:
  selector:
    app: yamtrack-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
