---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: yamtrack
  namespace: yamtrack
spec:
  encryptedData:
    SECRET: AgAUjnHOiKPGkDc6doMBVOApDrDofVJCCS0yHPrsIQCgShi+D9MvODEbavzKWFL7PgfhCNzC92PBuv81W300qMvnYSYKGiQ0M3pfUDfR48425T8LSWz8YOk/ZZV3kylqddP2KCEK62TBkJrU5hHpK78VOt20uUKrgXNxUwXnX1M3Ml/PmkH4Q2MhQNwtV2cPG5++Duin+9pTEldoXgKzOVl4hYk0MxoZlxyddtRqnYdeYu+W1igHenCf7wgc2evnxAf0MzzOqMQsAWKDvxiFK/RiG/uxckXhAN2gOzMKk3+I2m2+5gEGBGiy2vQscuJuHQSJIqjtn+hTkW4z7P7VZQ4FnyjFr9/84eXsFg7zIt9wJTLTpRddcgwNmFg9hvss31xeljbKoJTx01zyiIF+GiI0GAB6WpTKDK8vSt8O4qbYpQfoPDw1+xxcLQefYPdL7FjT7Q1PkcxPqhQgTxK3kpw2Vl6TzHY+AdlKGlxZ7T3lKfhmaN93Kb87O1yUYwZUhvXvMjXKqmQm12DGFnCWIhlebI7vxFUu218zffGe8xpbg57EI/6JFRWlXHkfWalR1AGweypNFBh3TiaUfk5cDmkjqpSe1hHUpF0Oy66Vz4csTzNUSmgHZglT1hjcFiLLwyCOaf0C8crmNXtbCJM0oM1o62ZVjrWfmvxcFsnPlXWX54eUbi+Esd+SlrK1t71s5RpfPAwOEJ+Y95k8HzG2VjcdNDK6yVok0qoB0MnVPWnAOHV/MhWQ2scQiwhtxiMILaNIQKSjApSWk0cTgnMWfxpz
  template:
    metadata:
      name: yamtrack
      namespace: yamtrack
