---
apiVersion: v1
kind: Service
metadata:
  name: yamtrack
  namespace: yamtrack
  labels:
    app: yamtrack
spec:
  selector:
    app: yamtrack
  ports:
    - name: http
      port: 8000
      targetPort: 8000
