---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCDGApyTOGYdw5jAMgUyTk2UNw4Iun/ZCF6PCqhWjZ+JI2cG/Wh86AnrJSYCXhe1M/6xrymcffaECpWdZaFTszR+5jCoaDKUIrviG3QRuoNfjfc2Ecc6zOFBCJabke4GNAQIq3RyVm+HWBejvEVhMCkxN7BBPHf2o+k9NYFbS79UVGmD5SPbMAobdSqZbzq//T57lIudOyIe6b2DhLT7lEI0LfgzwpD2Fif3b7V+X6GPDOaxcCqtPix7Kin15N6y2O9k5Hn4jSJX6HGwOCyGojZaTNUl18sXSLX0YOkGB1KgRwdoclDwQPbU2OBHdLjVw+sgQseuu0iaAGEkFcwPrlwJC8WF387OB8CVl31GPOypWjfHXPhSGjnWILXkuEUrUgpejqwA+Y32lzuSWHFPKcAUaEbKaBr8jo5h7QDvmwvUZs0c1M1Eanbpv4bvESj3ROyNM9x5El1g5Nawe702/C23/RAqkZekCmRgdx0PpWwnAKjlv26HyvFPXeTnmjrv2Xwf4WmSTIzyP0eaJDa41jcW0J8ZrlAIGTrPEpNYjxOP+p1r3qtDLg+3Sgo6u6E9S7aNWU4wM6tem3lJgArXSpBozRYn9b6rbfuNUrIaWUuhNE0zrg9cQTFFP8YQUPBQab5L5gM4pxZeinb7n3itQ3PYODrwUKdcWMX2/HRNZTg8dUvKOG9qAjUvQVkHhq8jdr7u/uJKa7sU/cdtKwE2WkwCG/swAJLj2w=
    admin-user: AgBT9VASGa1vtYY2PesXAOQg1DdsmmwAO0m2WUhR9hTdujIGI6Kp4MAPt6le29vMppSIIDhfN99Pm1FFGuexq7d2zhKxfAlDn2BotkU7aNyxqTBlyGg5TebfNwEsvs7iaBqyOFsnArY8/b+7rn0detqJJvitfH5Rt4G35GQcLbt0R/V5vFqyzwMgK0nK9Puvw4NB5I0Wbf+xfyNXhKe/bT39dTIoJ8fAGB72rtZNZLXW1T4ZS5ZN5EG7r8G2j/MQJpJyh6qFmeR0xhNV60plVG5osrrUXfdvYKII1D34QV93dFvnH6Z/wgFilz4TdSjqveHfsc4SZfhdX78Fteyih1kgh1Gwwjt9Eut5p5+Bw/uTwTlLWtYLBzG4Vl4DLkU4Pxp16bWsJjVQS6EOCQJurelfwFDDifuJMYHUhzKzKltZS/YLX8o1851yZ+syspzpOpvDNwNykOHNcv7URP/vwJ/vBc2E8Zqkin7Z7EqgHz5I3MvnvMLwlFeFhBIWfQ6YKqyaOvbr1stTLd6Q3UFcvkqL8N33IE7uyaJ6bV3wql+hk/4p3kTGLMj+ZjKq2TqKInTMIie3d8O9bmdUbxNS5CrzoCUbRrBzkUs3vBBZRxzrmke+GR++TCqJJwqtIOmPHjxbIy4UpuR7ESxBy/WJqG9VAtVdytqpgDjO/4TsFA8SrPwx7kJfgDVAeij4rB20aAqUGGoN5g==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
