---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-mullvad
  namespace: monitoring
spec:
  encryptedData:
    MULLVAD_ACCOUNT: AgBMNg1pLYFUzkb+jBcdwqmd9N4zrT2nUx5mWEzPfA5tpUEHkTPIgiiUMr/kuRg+C06hKDcGlnNl+zqvgCEalryPAUjxPUuA0qmdWEVyoRf4utUyyoMehCSkq4fDJ6nn1AG8KHO9KGREro8eEECNIm9ZAJbV+EEoVkftwMJn+xUU+SXQOJdLQ9UtyAegZBg2qxyM83xK4CcAB906EjeViQNh8LGcfr5kuanEqd7yKJQCyz/EZ7yq4FTAB/E+n3roQAEQwRuxpGqC7/muzNGZJ0Vbj16Bl4kumuEAZrzejsFho1Z4lAaGU88MRlx1J2+LtUWzAOlwNZ6o+c2+FplX6lbvGSoVr1Ef+EfW5RQ7CRSg8A13YHMDdQkOM1Gc0iEDhf4cC1nKTCt6JV6Hf7eLMmSbxD98XpLdq6U/UISEvDBgnwbWw6WKyQ1TXg3Gr9BfsggHleYzLevJlEeSI7NBBbatIB3bU+1oXIr71Pg8D1rqeHGopv4XkCh03szDJvPSQ1W7EWzATml6b/UeRKNrzJQvALcbvgcUamIcKBj2TXyDjyVyer0Z0HyLhsOVzzQkgBiUziWE2U2Z0yIJOruCHYwI4M+LAINz1WL0oMnjBVpLT/2P6aKiBEU5Bfn24xpxgPeMhaPHQv2Hx+mfH61ODbA2UyWUYn41tf5fuu1zKLi9E98XGQ2nBMDY5dxk4P9ACyf6XTgC/upLWjV5bQM=
  template:
    metadata:
      name: grafana-mullvad
      namespace: monitoring
