---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials-hetzner
  namespace: velero
spec:
  encryptedData:
    cloud: AgBdyq90CBIYi+Q+53xvqaQIUc0g7uIT/zVfI5Wjpf4yFC7VbcPV5+I0qjNyV9BrLWtP5rxPAtG/lPFmbZlbdXJGmWRfjlhkuO8o19QCi0qVk2P8b4PZQ7+41wgHPAhS5vdHG7X+FQmSSmh0orVJvrmw+SJ1DGTmaaJSB0MCyuV+zjCLdUdXJun1zCSR1+VQQw/b/8bh0F+mCVM6dncITD7PQCPPKSQgoPpN/rNxuBazNcgEeiTeH5CpRehTdrgFn/Ma082xhXH/cMg9lO3XxRwHmKB0XWfKnnC3rWfLKYPmfeCRJrzBNxSfVa9d8qLDq0TmfpeDOHEmxRZiMcQVhbP9tgHxactRLOp7BgN9GyV2NU323e6e9H5SLhyDGO6sOdDRKJFR+xiiX3mneVt0Itp+bxWcQA9Qw4/FM+SlnPwJgQv7LUZ0T62lKQyxjCGT1VJy/rjOnrxgqnGAbOn2MNStGAGDsILAlrwA0TlpnJsNz/dzYWBx4L6yG/23F5XpyaXUgdaeBCvDJ7inMJrkb9uCatU1AzgJIoAEJ0+rXITrRLRsD4qIoIl/+e5Yov1bIR9YrsbejbTFJovYnYLXw2tvanPTNQAde7Mn+Z9qCcla8YUCuVVRIhdImL5Et8mi0Bm3mvGtRjRtVnJ8hxProukV+tE9hRTp2TBhrPkyTHAecprc1AQxJE7z8CvBb0sNCcDYIqZrlqz5zi3QZ+fioD6OcMtWmpmuuU/K2lA/InebFBuE1ysc1t2zDFrgWDGjLuLLyLmZA9OYPs4lNH7LAEHzfpPjMEOp1/JrM9WYFQImJiNnrBax98snOSUMfx0CrT33qeqc6l6rk963mvgEbLo=
  template:
    metadata:
      name: velero-credentials-hetzner
      namespace: velero
