---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials-rustfs
  namespace: velero
spec:
  encryptedData:
    cloud: AgAdheOHKGc4r84IHnmVCZpfZ7aEI4Glo/FWh+rnp3ASSK9IOoB3pdJ97M0HrVM4kHYTZngu8Wyyb02IKyTSk5yTVMx+J+kMjf28U0Z3XjOQFVlhX+Rg6mc17CYHK0kVYa+FRnyhtaqvnV375sEL8qLFWLFZc8yNgTOqGc+MmIeUkWG9Y+C4xnAaYD+fWRe+b6nnZRFaQUnOGt/Ro8hBAf2Of7OXfoGDw2bMwAdGNMR1AtGnjRECFAQzIxDOwMeOSiU/cDKFbNnydp7pECecAYo+Gf1VL+cOkiNCERxoXHaACfJt2VDt3JsW+5B6Kgg7GGO8ipDaZtiVoVf+muYaGyo03ngG3cS+4oobcy4vuuUxrAjuHqtaK4CmJVCmZlhN45HEq6MRQxwCF3m36UuE8fX1PJRE1J7V8x5kbz77hKjbzWKeUT7CgPQN371wKibUf0gRVwj3lQpDz09nlULG5GQ8QdFOAQF/aOrKkHzj5vctQubOGz+ql/0iQbm/scJElnFF2WMUVIPU2hE5Yz0mELeJoDXG57huEfZqBcQQZ8HRChBCUZ5zPL/Ol8/H+/+sxRK5joQecXZbUFT9n/8/CTwtpIluDvAJKes6lPqtBrWSqBiIOVpjwOJ/gFrGMUhfP7mZ578rNxvZUA+Oo4UplVOBCTZc1qD1e8VZnnt3JOpgNHhYX7fvFuXstpuf5M0BvHmv2oVumptVRUJJMKCkXzArYH1u+jLRoW2p2zaAkKEORZrqclFp0JZxVvzgTPd78YL1QIITJ/EjMCuY44uA+VQhCa/ZRtYGITVbfK60F2bB96O8E/XHTxIRsdR+adHdmFS0OdTEp5K5PrLJZVyTPmYx
  template:
    metadata:
      name: velero-credentials-rustfs
      namespace: velero
