---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-sse-c-key
  namespace: velero
spec:
  encryptedData:
    key: AgALCx5diCzavDY6eNCUQ9o743VaVaaA6ZrYim1aqgATben6VY6ONNCqwEuH8TWm+d3i45Yb/BFZr12kLNGu70tCJuCxi5VkmuR2f+gd313stDSUY1fJzhx4Xum6gv+THgYXuo/m1o6dvExQs62Ky4Peu1TimbJ0eCKqZhP5wipUCrhdiYjeWmN0MbOEUluK5A//6YHlMiKTGo+BUhRnAqv4HHhUiOHsuAlgmm8mVtvYzirLpjJ2Us079CFjZRwGChJj7r1e5ceqwWGbTYK6q/d5cO+T7CpstXXrbu13TiklUO3iEuqpeyDy0Mbx9dPSNMpZzlCmLu9hG2AGZxCgjCPvqc758V68vbQABgRHzBqd/57wNZG6rrjYmYtos4a/A2jO1tGbv7L1EVEX72H45Qw6U0ewnloVH8+9DFCJx+0IBI/nrjMcPlW5MM5Dp55h+v719isTOjgiN0s+Go040bussja29lvz0EpfQ0EAY8iRlulmO0GJ6degBKFxlmSM9kQxTBR3KmuK1bK0ywg0jIpE6jMuzhSaveo8DpPU3mZN1hcQhXu76p3xePk9W/f+IholZk0i+MNZvgYJ/1NH22A3gH3uKuKvK6FGOAeJVqojjjJ0YAXoNnJzv8HVVFTkSepi6uA1yNpb+oM/h93VMrPIMEQAQE5Tm7A6iNMe117S+pOlZVSo/sSVGt7ynhkm2fz9weieq+98bRRgVGkt3ZVCEsZcSkyWhVtEkpqbTKfA7Q==
  template:
    metadata:
      name: velero-sse-c-key
      namespace: velero
