---
apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-volume-policy
  namespace: velero
data:
  policy.yaml: |
    version: v1
    volumePolicies:
    - conditions:
        capacity: "500Gi,"
      action:
        type: skip
